name: Mikage Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build python3-pip libvulkan-dev
        pip install conan --break-system-packages

    - name: Configure Conan profile
      run: |
        mkdir -p ~/.conan2/profiles
        cat > ~/.conan2/profiles/default << EOL
        [platform_requires]
        boost/1.80.0
        cryptopp/8.5.0
        sdl/2.0.20
        range-v3/0.11.0
        catch2/2.13.7
        libunwind/1.8.0

        [conf]
        tools.build:cflags=["-std=gnu17"]
        EOL

    - name: Create build directory
      run: mkdir build && cd build

    - name: Install Conan dependencies
      working-directory: build
      run: conan install .. -of . --build=missing -s build_type=Release

    - name: Configure CMake
      working-directory: build
      run: cmake .. -G Ninja --toolchain conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: build
      run: ninja

    - name: Install
      working-directory: build
      run: sudo ninja install
